HEADERS += note.hpp
HEADERS += melody.hpp
HEADERS += note_player.hpp

HEADERS += note_player_gpio.hpp
SOURCES += note_player_gpio.cpp

HEADERS += melody.cpp

RELATIVE := ..
include $(RELATIVE)/makefile.due
include maakfile	